apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: metric
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: health
      protocol: TCP
      port: 8081
      targetPort: 8081