# permissions for end users to view clustermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: clustermanager-viewer-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermanagers/status
  verbs:
  - get
