# permissions for end users to edit genaideployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: genaideployment-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - genaideployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - genaideployments/status
  verbs:
  - get
