# permissions for end users to view searchheadclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: searchheadcluster-viewer-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/status
  verbs:
  - get
