apiVersion: v1
kind: ConfigMap
metadata:
  name: sais-service-config
  labels:
    app: sais-service
data:
  SCS_TOKEN: ""
  IAC_URL: "auth.playground.scs.splunk.com"
  API_GATEWAY_URL: "api.playground.scs.splunk.com"
  PLATFORM_URL: "kuberay-operator.splunk-operator-system.cluster.local:8080" # ray service url 
  TELEMETRY_URL: "https://telemetry-splkmobile.kube-bridger"
  TELEMETRY_ENV: ""
  TELEMETRY_REGION: "region-iad10"
  ENABLE_AUTHZ: "false"
  SCPAUTH_SECRET_PATH: "/etc/sais-service-secret"
  SAIA_API_VERSION: "v1"
  PLATFORM_VERSION: "v1"
  AUTH_PROVIDER: ""
  ENABLE_AUTHN: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: sais-service-secret
  labels:
    app.kubernetes.io/name: sais
    app.kubernetes.io/managed-by: sok
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded 'admin'
  password: c2VjcmV0  # Base64 encoded 'secret'
  AWS_ACCESS_KEY_ID: YWRtaW4=
  AWS_SECRET_ACCESS_KEY: YWRtaW4=
  AWS_SECURITY_TOKEN: YWRtaW4=
  AWS_SESSION_TOKEN: YWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-auth-secret
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: sok
type: Opaque
data:
  username: "MEQzaWdUNlpBS0lKdzdtZ3VmMEdtdlNmZ012eTQ0UEg="
  password: "R04zTnpZNU8xWTRRbEhVcmdlazR6Y1AzREUzUUFPOXI="
  AUTHENTICATION_APIKEY_ENABLED: dHJ1ZQo= # true
  AUTHENTICATION_APIKEY_ALLOWED_KEYS:  dml2ZWstc2VjcmV0LWtleSxhcmp1bi1zZWNyZXQta2V5Cg== #'vivek-secret-key,arjun-secret-key'
  AUTHENTICATION_APIKEY_USERS:  dml2ZWtyQHNwbHVuay5jb20sdml2ZWtyCg== #'vivekr@splunk.com,vivekr'
  AUTHORIZATION_ADMINLIST_READONLY_USERS:  aWFuLXNtaXRoLHJvYmVydGFAZG9lLmNvbQo= #'ian-smith,roberta@doe.com'

---
apiVersion: enterprise.splunk.com/v4
kind: GenAIDeployment
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: genaideployment-sample
spec:
  # TODO(user): Add fields here
  serviceAccount: genai-controller-manager
  saisService:
    secretRef: 
      name: sais-secret
    configMapRef: 
      name: sais-service-config
    image:  "vivekrsplunk/sait:v0.1.48"
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 512Mi
    replicas: 2
  bucket:
    endpoint: https://s3-us-west-2.amazonaws.com
    name: volume_app_repo
    path: genai-sok-bucket
    provider: aws
    region: us-west-2
    storageType: s3
  rayService:
    enabled: true
    image: "rayproject/ray:2.35.0-py311"
    headGroup:
      numCpus: "1"
    workerGroup:
      replicas: 2
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: region
                operator: In
                values:
                - us-west-2
  vectordbService:
    image: "cr.weaviate.io/semitechnologies/weaviate:1.26.1"
    secretRef:
      name: weaviate-auth-secret
    enabled: true
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    storage:
      storageClassName: "gp2"
      storageCapacity: "32Gi"
    replicas: 3
