---
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cluster-api-basic-auth
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded 'admin'
  password: c2VjcmV0  # Base64 encoded 'secret'
---
apiVersion: enterprise.splunk.com/v4
kind: GenAIDeployment
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: genaideployment-sample
spec:
  # TODO(user): Add fields here
  #serviceAccount: test-controller-manager
  saisService:
    image:  "vivekrsplunk/sais-api:0.0.1"
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 512Mi
    replicas: 2
  bucket:
    endpoint: https://s3-us-west-2.amazonaws.com
    name: volume_app_repo
    path: helm-test-c3-with-apps-testnew
    provider: aws
    region: us-west-2
    storageType: s3
  rayService:
    enabled: true
    image: "rayproject/ray:2.6.1"
    headGroup:
      numCpus: "4"
    workerGroup:
      replicas: 2
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 512Mi
  vectordbService:
    image: "cr.weaviate.io/semitechnologies/weaviate:1.26.1"
    secretRef:
      name: weaviate-cluster-api-basic-auth
    enabled: true
    resources:
      limits:
        cpu: "4"
        memory: "8Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    storage:
      storageClassName: "standard"
      storageCapacity: "32Gi"
    replicas: 3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values:
                    - "gpu-node-1"
                    - "gpu-node-2"
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    serviceTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: weaviate
          app.kubernetes.io/managed-by: Helm
      spec:
        type: LoadBalancer
        ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 8080
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "DoNotSchedule"
        labelSelector:
          matchLabels:
            app: weaviate
