apiVersion: v1
kind: ConfigMap
metadata:
  name: sais-service-config
  labels:
    app: sais-service
data:
  IAC_URL: "auth.playground.scs.splunk.com"
  API_GATEWAY_URL: "api.playground.scs.splunk.com"
  PLATFORM_URL: "ml-platform-cyclops.dev.svc.splunk8s.io"
  TELEMETRY_URL: "https://telemetry-splkmobile.kube-bridger"
  TELEMETRY_ENV: "local"
  TELEMETRY_REGION: "region-iad10"
  ENABLE_AUTHZ: "false"
  AUTH_PROVIDER: "scp"
---
apiVersion: v1
kind: Secret
metadata:
  name: sais-secret
  labels:
    app.kubernetes.io/name: sais
    app.kubernetes.io/managed-by: sok
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded 'admin'
  password: c2VjcmV0  # Base64 encoded 'secret'
---
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cluster-api-basic-auth
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: sok
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded 'admin'
  password: c2VjcmV0  # Base64 encoded 'secret'
---
apiVersion: enterprise.splunk.com/v4
kind: GenAIDeployment
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: genaideployment-sample
spec:
  # TODO(user): Add fields here
  serviceAccount: genai-controller-manager
  saisService:
    secretRef: 
      name: sais-secret
    configMapRef: 
      name: sais-service-config
    image:  "vivekrsplunk/saia-api:0.0.1"
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    replicas: 2
  bucket:
    endpoint: https://s3-us-west-2.amazonaws.com
    name: volume_app_repo
    path: genai-sok-bucket
    provider: aws
    region: us-west-2
    storageType: s3
  rayService:
    enabled: true
    image: "rayproject/ray:2.6.1"
    headGroup:
      numCpus: "1"
    workerGroup:
      replicas: 2
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
  vectordbService:
    image: "cr.weaviate.io/semitechnologies/weaviate:1.26.1"
    secretRef:
      name: weaviate-cluster-api-basic-auth
    enabled: true
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "512Mi"
    storage:
      storageClassName: "standard"
      storageCapacity: "32Gi"
    replicas: 3
