apiVersion: enterprise.splunk.com/v3
kind: IndexerCluster
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: indexercluster-sample
spec:
  # TODO(user): Add fields here
